[build] 
command = "nuxi build --no-prerender"
publish = ".output/public"
functions = ".output/server"

[[headers]]
for = "/*"
[headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    